//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M3_Uditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M3_Uditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _71cb68ce49ae4a7ebafc9f751863c134 {
            get {
                object obj = ResourceManager.GetObject("_71cb68ce49ae4a7ebafc9f751863c134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _74H8 {
            get {
                object obj = ResourceManager.GetObject("_74H8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap About {
            get {
                object obj = ResourceManager.GetObject("About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddButton {
            get {
                object obj = ResourceManager.GetObject("AddButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CheckLinks {
            get {
                object obj = ResourceManager.GetObject("CheckLinks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap epg_icon {
            get {
                object obj = ResourceManager.GetObject("epg_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Export {
            get {
                object obj = ResourceManager.GetObject("Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExportAsM3U {
            get {
                object obj = ResourceManager.GetObject("ExportAsM3U", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Favorites {
            get {
                object obj = ResourceManager.GetObject("Favorites", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FavoritesYellow {
            get {
                object obj = ResourceManager.GetObject("FavoritesYellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FilePath {
            get {
                object obj = ResourceManager.GetObject("FilePath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #dabeiTV;#dabeiTV.de;3
        ///1-2-3.tv HD;123.tv.de;3351
        ///13th Street;13thStreet.de;148343
        ///3+;3plus.ch;9817
        ///3sat;3sat.de;134767
        ///4+ HD;4plus.ch;1182
        ///5+ HD;5plus.ch;798
        ///6+ HD;6plus.ch;340
        ///Allgäu TV;AllgauTV.de;997
        ///Animal Planet;AnimalPlanet.de;50795
        ///ANIXE SD;Anixe.de;2305
        ///ANIXE Serie HD;AnixeSerie.de;7029
        ///ARCADIA World HD;ARCADIAWorld.at;3470
        ///ard-alpha;ARD-alpha.de;41910
        ///ARTE;ARTE.de;107544
        ///AstroTV;AstroTV.de;133
        ///ATV;ATV.de;121309
        ///ATV2;ATV2.at;27293
        ///Auftanken TV;AuftankenTV.ch;8
        ///Augsburg TV (a.tv); [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string germany {
            get {
                return ResourceManager.GetString("germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap group_not_visible {
            get {
                object obj = ResourceManager.GetObject("group_not_visible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap group_visible {
            get {
                object obj = ResourceManager.GetObject("group_visible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icojam_Blue_Bits_Arrow_down_256 {
            get {
                object obj = ResourceManager.GetObject("Icojam-Blue-Bits-Arrow-down.256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icojam_Blue_Bits_Arrow_up_256 {
            get {
                object obj = ResourceManager.GetObject("Icojam-Blue-Bits-Arrow-up.256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_deutschland_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_deutschland_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_flagge_von_europa_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_flagge_von_europa_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_frankreich_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_frankreich_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_großbritannien_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_großbritannien_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_italien_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_italien_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_niederlande_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_niederlande_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_turkei_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_turkei_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_vereinigte_arabische_emirate_40 {
            get {
                object obj = ResourceManager.GetObject("icons8_vereinigte_arabische_emirate_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewFile {
            get {
                object obj = ResourceManager.GetObject("NewFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile {
            get {
                object obj = ResourceManager.GetObject("OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayButton {
            get {
                object obj = ResourceManager.GetObject("PlayButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveButton {
            get {
                object obj = ResourceManager.GetObject("RemoveButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveFile {
            get {
                object obj = ResourceManager.GetObject("SaveFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die #dabeiTV;#dabeiTV.de;3
        ///1-2-3.tv HD;123.tv.de;3351
        ///13th Street;13thStreet.de;148343
        ///3+;3plus.ch;9817
        ///3sat;3sat.de;134767
        ///4+ HD;4plus.ch;1182
        ///5+ HD;5plus.ch;798
        ///6+ HD;6plus.ch;340
        ///Allgäu TV;AllgauTV.de;997
        ///Animal Planet;AnimalPlanet.de;50795
        ///ANIXE SD;Anixe.de;2305
        ///ANIXE Serie HD;AnixeSerie.de;7029
        ///ARCADIA World HD;ARCADIAWorld.at;3470
        ///ard-alpha;ARD-alpha.de;41910
        ///ARTE;ARTE.de;107544
        ///AstroTV;AstroTV.de;133
        ///ATV;ATV.de;121309
        ///ATV2;ATV2.at;27293
        ///Auftanken TV;AuftankenTV.ch;8
        ///Augsburg TV (a.tv); [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string SmartIPTV {
            get {
                return ResourceManager.GetString("SmartIPTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StreamOffline {
            get {
                object obj = ResourceManager.GetObject("StreamOffline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StreamOnline {
            get {
                object obj = ResourceManager.GetObject("StreamOnline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StreamUnkown {
            get {
                object obj = ResourceManager.GetObject("StreamUnkown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .black;sony-turbo;13688
        ///.red;set;23133
        ///.red HD;set-hd;2718
        ///.sci-fi;axn;47114
        ///+ТВ;+tv;1
        ///1 TV GE;FirstChannel.ge;871
        ///1+1;1p1;10112
        ///1+1 Международный;1p1_int;2049
        ///1HD;1hdru;16964
        ///2 TV GE;2TV.ge;139
        ///2+2;2p2;5666
        ///21TV AM;21TV.am;4423
        ///24 (Телеканал новостей 24);news24;37048
        ///2х2;2x2;18451
        ///2х2 (+2);2x2+2;256
        ///2х2 (+4);2x2+4;16
        ///2х2 (+7);2x2+7;26
        ///34 канал (Днепр);34kanal;58
        ///36,6 TV;36-6-tv;431
        ///360 Новости;360-news;3207
        ///360°;podmoskovie;28307
        ///360TuneBox;360-tunebox;1172
        ///365 дней ТВ;365dney;7387
        ///4 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ussr {
            get {
                return ResourceManager.GetString("ussr", resourceCulture);
            }
        }
    }
}
